apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kotlin.serviceName }}
  namespace: {{ .Values.kotlin.namespace }}
spec:
  selector:
    app: {{ .Values.kotlin.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
